AppBundle\Entity\Account:
    type: entity
    table: accounts
    repositoryClass: AppBundle\Services\AccountService
    id:
        name:
            type: string
    fields:
        abi:
            type: json
            nullable: true
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
