AppBundle\Entity\Action:
    type: entity
    table: actions
    repositoryClass: AppBundle\Services\ActionService
    id:
        id:
            type: integer
    fields:
        data:
            type: json
            nullable: true
        name:
            type: string
        account:
            type: string
        parentId:
            type: integer
    manyToOne:
        transaction:
            targetEntity: AppBundle\Entity\Transaction
    oneToMany:
        authorizations:
          targetEntity: AppBundle\Entity\ActionAccount
          mappedBy: action