AppBundle\Entity\Block:
    type: entity
    table: blocks
    repositoryClass: AppBundle\Services\BlockService
    id:
        id:
            type: string
    fields:
        blockNumber:
            type: integer
        prevBlockId:
            type: string
        irreversible:
            type: boolean
        timestamp:
            type: datetime
        transactionMerkleRoot:
            type: string
        actionMerkleRoot:
            type: string
        producer:
            type: string
        numTransactions:
            type: integer
        version:
            type: integer
        newProducers:
            type: json
            nullable: true
        confirmed:
            type: integer
