AppBundle\Entity\Transaction:
    type: entity
    table: transactions
    repositoryClass: AppBundle\Services\TransactionService
    id:
        id:
            type: string
    fields:
        refBlockPrefix:
            type: integer
        pending:
            type: boolean
        blockId:
            type: integer # todo: block_id from Block?
        numActions:
            type: integer
        expiration:
            type: datetime
        createdAt:
            type: datetime
        updatedAt:
            type: datetime