AppBundle\Entity\Vote:
    type: entity
    table: votes
    repositoryClass: AppBundle\Services\VoteService
    id:
        account:
            associationKey: true
    fields:
        votes:
            type: json
    oneToOne:
        account:
            targetEntity: AppBundle\Entity\Account